input {
file {
path => "/logs/apache_logs.log"
start_position => "beginning"
sincedb_path => "/dev/null"
ecs_compatibility => "disabled"
}
}
filter {
grok {
match => { "message" => "%{COMBINEDAPACHELOG}" }
ecs_compatibility => "disabled"
}
date {
match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
target => "@timestamp"
}
geoip {
source => "clientip"
target => "geoip"
ecs_compatibility => "disabled"
}
useragent {
source => "agent"
target => "useragent"
ecs_compatibility => "disabled"
}
}
output {
elasticsearch {
hosts => ["http://elasticsearch:9200"]
index => "apache-logs-%{+YYYY.MM.dd}"
}
stdout {
codec => rubydebug
}
}